apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: messaging-app.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: messaging-app-service
                port:
                  number: 8000
